"""Report Manager - Export Reports for Clients"""
import json
import csv
from datetime import datetime
from pathlib import Path
from .utils import DATA_DIR, log, log_error

REPORTS_DIR = DATA_DIR / "reports"

class ReportManager:
    def __init__(self):
        self.reports_dir = REPORTS_DIR
        self.reports_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_broadcast_report(self, campaign_name: str, stats: dict, 
                                   members: list = None, format: str = "txt") -> str:
        """Generate broadcast report for client"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"broadcast_report_{campaign_name}_{timestamp}"
        
        if format == "txt":
            return self._generate_txt_report(filename, campaign_name, stats, members)
        elif format == "csv":
            return self._generate_csv_report(filename, campaign_name, stats, members)
        elif format == "json":
            return self._generate_json_report(filename, campaign_name, stats, members)
        
        return None
    
    def _generate_txt_report(self, filename: str, campaign_name: str, 
                              stats: dict, members: list = None) -> str:
        """Generate TXT report"""
        filepath = self.reports_dir / f"{filename}.txt"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("=" * 60 + "\n")
            f.write("       TG PRO QUANTUM - BROADCAST REPORT\n")
            f.write("=" * 60 + "\n\n")
            
            f.write(f"Campaign: {campaign_name}\n")
            f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            
            f.write("-" * 60 + "\n")
            f.write("BROADCAST STATISTICS\n")
            f.write("-" * 60 + "\n")
            f.write(f"Messages Sent: {stats.get('sent', 0)}\n")
            f.write(f"Messages Failed: {stats.get('failed', 0)}\n")
            f.write(f"Success Rate: {stats.get('success_rate', 0):.1f}%\n\n")
            
            if members:
                f.write("-" * 60 + "\n")
                f.write(f"SCRAPED MEMBERS: {len(members)}\n")
                f.write("-" * 60 + "\n")
                for member in members[:50]:  # Show first 50
                    f.write(f"• {member.get('username', 'N/A')} - {member.get('first_name', 'N/A')}\n")
                if len(members) > 50:
                    f.write(f"... and {len(members) - 50} more\n")
            
            f.write("\n" + "=" * 60 + "\n")
            f.write("Generated by TG PRO QUANTUM v5.0.0\n")
            f.write("=" * 60 + "\n")
        
        log(f"Report generated: {filepath}", "success")
        return str(filepath)
    
    def _generate_csv_report(self, filename: str, campaign_name: str,
                              stats: dict, members: list = None) -> str:
        """Generate CSV report"""
        filepath = self.reports_dir / f"{filename}.csv"
        
        with open(filepath, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            
            # Header
            writer.writerow(["TG PRO QUANTUM - Broadcast Report"])
            writer.writerow(["Campaign", campaign_name])
            writer.writerow(["Date", datetime.now().strftime('%Y-%m-%d %H:%M:%S')])
            writer.writerow([])
            
            # Stats
            writer.writerow(["Statistic", "Value"])
            writer.writerow(["Messages Sent", stats.get('sent', 0)])
            writer.writerow(["Messages Failed", stats.get('failed', 0)])
            writer.writerow(["Success Rate", f"{stats.get('success_rate', 0):.1f}%"])
            writer.writerow([])
            
            # Members
            if members:
                writer.writerow(["Scraped Members"])
                writer.writerow(["Username", "First Name", "ID", "Phone"])
                for member in members:
                    writer.writerow([
                        member.get('username', ''),
                        member.get('first_name', ''),
                        member.get('id', ''),
                        member.get('phone', '')
                    ])
        
        log(f"CSV report generated: {filepath}", "success")
        return str(filepath)
    
    def _generate_json_report(self, filename: str, campaign_name: str,
                               stats: dict, members: list = None) -> str:
        """Generate JSON report"""
        filepath = self.reports_dir / f"{filename}.json"
        
        report = {
            "campaign": campaign_name,
            "date": datetime.now().isoformat(),
            "statistics": {
                "sent": stats.get('sent', 0),
                "failed": stats.get('failed', 0),
                "success_rate": stats.get('success_rate', 0)
            },
            "scraped_members": members or []
        }
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        
        log(f"JSON report generated: {filepath}", "success")
        return str(filepath)
    
    def get_all_reports(self) -> list:
        """Get list of all reports"""
        reports = []
        if self.reports_dir.exists():
            for f in self.reports_dir.glob("broadcast_report_*"):
                reports.append({
                    "filename": f.name,
                    "path": str(f),
                    "created": datetime.fromtimestamp(f.stat().st_ctime).isoformat()
                })
        return reports


# Global instance
report_manager = ReportManager()
__all__ = ["ReportManager", "report_manager"]