-- ─────────────────────────────────────────────────────────────────────────────
-- TG PRO QUANTUM – UAT Test Data
-- Load into the staging database before running UAT:
--   psql -h <host> -U tgpq_staging -d tg_quantum_staging -f uat_test_data.sql
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ── Admin client ──────────────────────────────────────────────────────────────
-- Password: UATAdmin2024!  (bcrypt hash below is for reference; replace with a
-- real hash generated by the application's hash_password() utility)
INSERT INTO clients (name, email, hashed_password, api_key, is_admin, status, plan_type, created_at, updated_at)
VALUES (
    'UAT Admin',
    'uat-admin@tg-pro-quantum.app',
    '$2b$12$placeholderAdminHashReplaceBeforeUAT00000000000000000000',
    'uat-admin-api-key-replace-me-00000000000000000000000000001',
    TRUE,
    'active',
    'enterprise',
    NOW(),
    NOW()
)
ON CONFLICT (email) DO NOTHING;

-- ── Sample clients (3) ────────────────────────────────────────────────────────
-- Password for all test clients: UATClient2024!
INSERT INTO clients (name, email, hashed_password, api_key, is_admin, status, plan_type, created_at, updated_at)
VALUES
    (
        'UAT Client Alpha',
        'alpha@uat-test.app',
        '$2b$12$placeholderClientHashReplaceBeforeUAT0000000000000000001',
        'uat-client-alpha-api-key-replace-me-0000000000000000001',
        FALSE, 'active', 'pro', NOW(), NOW()
    ),
    (
        'UAT Client Beta',
        'beta@uat-test.app',
        '$2b$12$placeholderClientHashReplaceBeforeUAT0000000000000000002',
        'uat-client-beta-api-key-replace-me-00000000000000000002',
        FALSE, 'active', 'pro', NOW(), NOW()
    ),
    (
        'UAT Client Gamma',
        'gamma@uat-test.app',
        '$2b$12$placeholderClientHashReplaceBeforeUAT0000000000000000003',
        'uat-client-gamma-api-key-replace-me-0000000000000000003',
        FALSE, 'active', 'basic', NOW(), NOW()
    )
ON CONFLICT (email) DO NOTHING;

-- ── Account groups (5) ────────────────────────────────────────────────────────
-- Linked to UAT Client Alpha (adjust client_id after insert if needed)
INSERT INTO account_groups (name, feature_type, status, config, created_at, updated_at)
SELECT
    grp.name,
    grp.feature_type::account_group_feature_type,
    'active'::account_group_status,
    grp.config::jsonb,
    NOW(),
    NOW()
FROM (VALUES
    ('UAT_Broadcast_Group_01', 'broadcast', '{"max_per_hour": 60, "max_per_day": 500}'),
    ('UAT_Broadcast_Group_02', 'broadcast', '{"max_per_hour": 80, "max_per_day": 600}'),
    ('UAT_Finder_Group_01',    'finder',    '{"max_per_hour": 100}'),
    ('UAT_Scrape_Group_01',    'scraper',   '{"max_per_hour": 200}'),
    ('UAT_Mixed_Group_01',     'broadcast', '{"max_per_hour": 40, "max_per_day": 300}')
) AS grp(name, feature_type, config)
ON CONFLICT DO NOTHING;

-- ── Telegram accounts (20 sample) ────────────────────────────────────────────
-- Linked to UAT Client Alpha; adjust client_id after insert if needed
WITH alpha_client AS (
    SELECT id FROM clients WHERE email = 'alpha@uat-test.app' LIMIT 1
)
INSERT INTO telegram_accounts (client_id, name, phone, status, health_score, created_at, updated_at)
SELECT
    alpha_client.id,
    'UAT Account ' || phone_suffix.n,
    '+1555' || LPAD(phone_suffix.n::text, 7, '0'),
    'active'::account_status,
    85.0 + (phone_suffix.n % 15),
    NOW(),
    NOW()
FROM alpha_client, generate_series(1, 20) AS phone_suffix(n)
ON CONFLICT DO NOTHING;

-- ── Sample campaigns (10) ─────────────────────────────────────────────────────
WITH alpha_client AS (
    SELECT id FROM clients WHERE email = 'alpha@uat-test.app' LIMIT 1
)
INSERT INTO campaigns (
    client_id, name, message_text, status, mode,
    delay_min, delay_max, sent_count, failed_count,
    created_at, updated_at
)
SELECT
    alpha_client.id,
    'UAT Campaign ' || c.n,
    'Hello from UAT Campaign ' || c.n || '! This is a test broadcast message.',
    CASE c.n % 3
        WHEN 0 THEN 'draft'::campaign_status
        WHEN 1 THEN 'completed'::campaign_status
        ELSE 'draft'::campaign_status
    END,
    'once'::campaign_mode,
    27.0,
    33.0,
    CASE WHEN c.n % 3 = 1 THEN (c.n * 5) ELSE 0 END,
    CASE WHEN c.n % 3 = 1 THEN (c.n % 3) ELSE 0 END,
    NOW(),
    NOW()
FROM alpha_client, generate_series(1, 10) AS c(n)
ON CONFLICT DO NOTHING;

-- ── Sample groups (50) ───────────────────────────────────────────────────────
WITH alpha_client AS (
    SELECT id FROM clients WHERE email = 'alpha@uat-test.app' LIMIT 1
)
INSERT INTO groups (client_id, username, title, member_count, is_active, created_at, updated_at)
SELECT
    alpha_client.id,
    'uat_group_' || g.n,
    'UAT Test Group ' || g.n,
    1000 + (g.n * 50),
    TRUE,
    NOW(),
    NOW()
FROM alpha_client, generate_series(1, 50) AS g(n)
ON CONFLICT DO NOTHING;

COMMIT;

-- ── Verification query ────────────────────────────────────────────────────────
SELECT
    (SELECT COUNT(*) FROM clients WHERE email LIKE '%uat%')          AS uat_clients,
    (SELECT COUNT(*) FROM account_groups WHERE name LIKE 'UAT_%')    AS uat_account_groups,
    (SELECT COUNT(*) FROM telegram_accounts WHERE name LIKE 'UAT %') AS uat_accounts,
    (SELECT COUNT(*) FROM campaigns WHERE name LIKE 'UAT %')         AS uat_campaigns,
    (SELECT COUNT(*) FROM groups WHERE username LIKE 'uat_%')        AS uat_groups;
